### ISSUE TITLE
Color each particle individually?

### ISSUE THREAD

**Issue by zcanter** [pwambach/threejs-particle-shader#2]
Hello.

Great work!

Curious if we are able to color each particle individually?
I should add I am using the targetTexture to render positions. I am making a 3D data visualization of a climate model.

Thanks!

**Comment by pwambach** [comment]
Hey,

should the color depend on a value or do you want to specify a color for each point?

Both should be possible with a bit of work...

**Comment by zcanter** [comment]
Thanks for the reply!

Yes, I would like the color to depend on a value. That being said I do not mind specifying a color for each particle manually if that is easier. I don't mind doing the work, maybe you could point me in the right direction? I'm not really sure where to start. 

Thanks!

**Comment by pwambach** [comment]
It depends on wether you want to color your points depending on an "alreday existing" value like the position in space or its velocity etc., then you could just adjust the shader code to use the value as the new gl_FragColor.

On the other hand if you want to set a custom predefined color to every point you would have to create a new buffer with the color values or (probably better a texture where each pixel has the color for a specific point) and pass it to the shader. Read it out and output as gl_FragColot.

May I ask what your use case is, perhaps this makes it easier for me to understand the what your goals are.

Hope this helps a bit :)

Cheers

**Comment by zcanter** [comment]
Thank you for your response! 

I have a 3D dataset. It is a collection of sea surface temperatures in different regions around the globe. I am trying to make a 3D data visualization with the Y dimension color mapped to illustrate level of temperature. Currently I am using the temperature level as the Y axis successfully with your framework! I just need to find a way to do the color mapping. Sorry it's for an assignment I have at NASA-JPL in Pasadena, CA. I cannot use regular entities such as spheres or rectangles because they significantly slow down the visualization.

If I could map color off of position in space that would work! I would need to break it up into bins somehow I assume so that certain ranges of Y positions become certain colors.

**Comment by pwambach** [comment]
Ah I see, sounds like a cool project!

So to use the position data from your targetTexture as color input you have to change the display vertex and fragment shader code and build the project again by running `gulp webpack`.

The `display.vert.glsl` would have to look something like

```glsl
uniform sampler2D posTex;
uniform float pointSize;
uniform vec3 targetPosition;
varying float dist;
varying vec3 pos; // add pos as a varying to be passed to the fragment shader

void main() {
  pos = texture2D(posTex, position.xy).rgb; // set pos varying from targetTexture position
  dist = distance(targetPosition, pos);
  gl_PointSize = pointSize;
  gl_Position = projectionMatrix * modelViewMatrix * vec4(pos, 1.0);
}
```

and the `display.frag.glsl` shader:

```glsl
varying float dist;
varying vec3 pos; // insert position varying
uniform float alpha;

void main() {
  vec4 color;
  /*replace*/
  color = vec4(0.0, 1.0, 0.0, alpha);
  /*replace*/
  gl_FragColor = color;
}
```

After that you should be able to use `pos` in the configuration option "colorFunctionString" like for example:

```js
{
  colorFunctionString: "color = vec4(pos.x, pos.y, pos.z, alpha);"  // use coordinates for RGB 
}
```

Hope this works! It has been a long time that I have seen this code ;)

Another question: Are your points animated? If not maybe you should probably use just a three.js Points instance with a custom shader material. This project is based on particle animations with ping-ponging FBOs, so there's a lot of overhead if your not interested in animations. Nevertheless it should work!

Cheers

**Comment by pwambach** [comment]
Oh and the color values in 
```js
{
  colorFunctionString: "color = vec4(pos.x, pos.y, pos.z, alpha);"  // use coordinates for RGB 
}
```

should be between 0.0 and 1.0 so probably you'll have to map the position with something like `smoothstep` https://www.opengl.org/sdk/docs/man/html/smoothstep.xhtml

I guess in your case this would be:

`color = vec4(0.0, smoothstep(minY, maxY, pos.y), 0.0, 1.0);`

with minY/maxY your lowest and highest Y value.

**Comment by zcanter** [comment]
This works really nicely!!

I made the adjustments you mentioned and rebuilt it. I actually didn't need to use smoothness since the Y data is already normalized between 0 and 1.

I have been able to get a lot very cool color mapping effects with this technique - so many options! I really like the effect of just even using 1 color and the alpha.

Example:
`color = vec4(0.1, pos.y, 0.1, alpha);`

Anyway, Thanks a ton man - great framework!!

**Comment by zcanter** [comment]
I just wanted to follow up and say this technique is amazing because you can do things like this:

`float c = pos.y; if (pos.y < 0.5)  c = 1.0;  color = vec4(0.5, 0, c, 1);`

Which gives you fine control over coloring. Thanks for your help on this man!!

**Comment by pwambach** [comment]
cool, glad it worked out!

do you have a screenshot of the result? i'm just curious what people build with the project. if it's not public no problem :)

**Comment by zcanter** [comment]
I'm sorry I can't show anything :/
